### ISSUE TITLE
How is this tool different than other Python static analysis tools?

### ISSUE THREAD

**Issue by nashid** [dosisod/refurb#14]
There are many static analysis tools such as Pylint, pyflakes, mypy among many.

How is refurb different than other static analysis tools?

Looking forward to hear from you.

**Comment by chapmanjacobd** [comment]
I feel like this is not super useful compared to more powerful static analysis tools like you mentioned. But it did help me "fix" a few things. Will I keep it installed? No. Is it worth trying once? Maybe.

It offers some very opinionated guidance, for example:

```
Use `Path.cwd()` instead of `os.getcwd()`
Use `with suppress(Exception): ...` instead of `try: ... except: pass`
```

Nowhere in my code do I have a bare `except:`. I don't like this style anyway so this suggestion was not very meaningful.

But some of the suggestions were useful:

```
Use `not x` instead of `len(x) == 0`
Use `x` instead of `len(x) > 0`
```

Because I do that a lot; with the right data type it is unnecessary to use `len()` in those cases

```
Use `x` instead of `int(x)`
```

It shows this when using `int(` within a string interpolation. There are likely a few edge cases where you would not want to blindly remove int() even if, in the next millisecond, it will be cast to a string. But in my case this was helpful.

```
[FURB109]: Use `in (x, y, z)` instead of `in [x, y, z]`
```

This was helpful, though the performance improvements are doubtful. `refurb` should have a suggestions mode similar to pylint where it will inline the suggestion instead of making one go the long way via "`refurb --explain ERR`"

**Comment by dosisod** [comment]
I think this is a perfectly valid question! I hope to add a more complete comparison to the README file at some point, but in short:

[Black](https://github.com/psf/black) is more focused on the formatting and styling of the code (line length, trailing comas, indentation, and so on). It does a really good job of making other projects using Black look more or less the same. It doesn't do more complex things such as type checking or code smell/anti-pattern detection.

[flake8](https://github.com/pycqa/flake8) is also a linter, is very extensible, but performs a lot of semantic analysis-related checks as well, such as "unused variable", "break outside of a loop", and so on. It also checks PEP8 conformance. flake8 is built off of [pyflakes](https://github.com/PyCQA/pyflakes), though where the line is drawn between the two I don't exactly know (I have only ever used flake8).

[Pylint](https://github.com/PyCQA/pylint) has [a lot of checks](https://pylint.pycqa.org/en/latest/user_guide/messages/messages_overview.html) which cover a lot of ground, but in general, are focused on bad or buggy code, things which you probably didn't mean to do.

[Mypy](https://github.com/python/mypy), [Pyright](https://github.com/Microsoft/pyright), and [Pyre](https://github.com/facebook/pyre-check) are all type checkers, and basically just enforce types, ensures arguments match, functions are called in a type safe manner, and so on. They do much more then that, but that is the general idea. Refurb actually is built on top of Mypy, and uses its AST parser so that gets good type information.

And finally, Refurb. Refurb doesn't want you to throw out your old tools, since they cover different areas of your code, and serve a different purpose. I originally created Refurb because during code reviews, I would often see these small snippets which could be improved or tweaked to be more readable or more succinct, though no tool that I could find did this. Most of Refurb's checks make code more readable, more succinct, more expressive/declarative, and so on. Refurb is inspired by [clippy](https://github.com/rust-lang/rust-clippy), which is the built-in linter for Rust. As someone who doesn't use Rust very often, it was nice to learn that there is a nicer way of doing something, but not knowing how to look it up.

Hopefully this was helpful in answering your question!

**Comment by dosisod** [comment]
Thank you for the input @chapmanjacobd . Some things I will mention:

* The `with suppress(...)` check is indeed a style choice, but the error message saying `except: pass` is a bug (and is already on my fix list). It should read `except ExceptionXYZ: pass`, unless of course it is a bare exception.

* As far as I can tell, the `int(x)` check should not cause any issues, and if it does, it is probably a false-positive. If you use `int(x, base=16)`, no error will be emitted. Same goes for `str(x)`, `float(x)`, and the rest of the built-ins.

The suggestion to put the `--explain` information on the next line is helpful, since I am looking to reduce the horizontal space of the error messages as is. I prefer single-line error messages, but others might not, so there should be some way to customize the output a bit.

**Comment by pums974** [comment]
Hi, it would be nice to know how refurb is different from pyupgrade https://github.com/asottile/pyupgrade

**Comment by dosisod** [comment]
@pums974 , quoting myself from the [Hackernews article](https://news.ycombinator.com/item?id=33004797) about Refurb:

> From looking at the README, Refurb is more focused on simplifying the codebases, making them more expressive, whereas pyupgrade seems to have the goal of upgrading you from version A to version B (specifically Python 2 to 3). Near the bottom there are some newer Python version (3.6+) related upgrades, which I was considering adding to Refurb. I expect there to be some overlap between my project and some of the existing projects out there, so I will have to weight the costs of adding these in vs leaving them out.

In short, pyupgrade is more focused on upgrading from Python 2 to 3, whereas Refurb assumes you are already on Python 3. Pyupgrade has some Python 3 functionality, though it is limited in scope, and more focused on small improvements, such as using `list[T]` instead of `List[T]` and so on. Refurb is linting more high level code smells, non-pythonic code, and so on.

Hope that answers your question!

**Comment by henryiii** [comment]
> I don't like this style anyway so this suggestion was not very meaningful.

I'm not so used to it as well, but that's probably from exposure to Python <3.4. This code:

```python
try:
    do_stuff()
except (MyErr1, MyErr2):
    pass
```

Really does read better, I think, as:

```python
with contextlib.suppress(MyErr1, MyErr2):
    do_stuff()
```

Besides being two lines shorter, if ``do_stuff` is multiple lines, it's much easier to see why there's a block, and that the that error will be suppressed without scrolling to the end, and it looks a lot like PyTest's `with raises` construct, as well. The only downside is it might look like the error is somehow ignored completely and allows the lines _inside_ the block to keep running (which is impossible, it would be undefined), but that's a small issue & will go away with more exposure, I think.

And `Path.cwd()` returns a path, wile `os.getcwd()` returns a string, so they really aren't swappable, but I'm happy to have anything help me to move to more pathlib. :) There are a few places where you have to use old path handling due to performance, but generally, pathlib is so much nicer.

**Comment by henryiii** [comment]
Actual example:

```python
        try:
            with open(os.path.join(CMAKE_BUILD_DIR(), "CMakeCache.txt"), encoding="utf-8") as fp:
                for line in fp:
                    if line.startswith(variable_name):
                        return line.split("=", 1)[-1].strip()
        except OSError:
            pass
```

vs.

```python
        with contextlib.suppress(OSError):
            with open(os.path.join(CMAKE_BUILD_DIR(), "CMakeCache.txt"), encoding="utf-8") as fp:
                for line in fp:
                    if line.startswith(variable_name):
                        return line.split("=", 1)[-1].strip()
```

I resisted temptation and didn't join the context managers with a Python 3.10's parentheses support, but you could join them and reduce a nesting level, too!

Ignore the old ugly pathlib-less code there. ;)

**Comment by dosisod** [comment]
If you want to get really fancy, here's another option:

```python
with contextlib.suppress(OSError):
    for line in Path(CMAKE_BUILD_DIR() / "CMakeCache.txt").read_text("utf8").splitlines():
        if line.startswith(variable_name):
            return line.split("=", 1)[-1].strip()
```

Also, I don't like that the `Path.cwd()` check is forcing people to use `Path` objects. I prefer it, but changing types from `str` to `Path` is a bit forceful, so I think it would be best to disable that check by default. Refurb should only be offering drag-and-drop replacements. Checks which require more suggestive upgrades (ie, a type change) should be opt-in.
