### ISSUE TITLE
[Bug]: "error: Source file found twice under different module names" when using src layout

### ISSUE THREAD

**Issue by jeffsawatzky** [dosisod/refurb#246]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

When I run refub in a repository that used poetry with the --src layout I get "Source file found twice" errors.

```bash
refurb .
```

Emits the following error:

```
src/app/domain/ports/repositories.py: error: Source file found twice under different module names: "src.app.domain.ports.repositories" and "app.domain.ports.repositories"
```

### Version Info

```shell
Refurb: v1.15.0
Mypy: v1.1.1
```

### Python Version

Python 3.11.2

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Hi, thank you for opening this issue! A couple of follow up questions:

* Is the source code for this application open source? Being able to see the full project structure would help
* What directory are you running Refurb from?
* What happens if you run `mypy .` from the directory you ran Refurb from?
* What happens if you replace `.` with a different directory?

Because Refurb is built on top of mypy that means we use mypy's module loading system, and I have noticed it can have this issue. One work-a-round is to run Refurb like so:

```
$ refurb . -- --exclude some/folder/here
```

Which will tell Mypy to exclude a certain folder. This is less than ideal, but it should help at least pin-point what folder is causing Mypy to fail.

**Comment by lukehsiao** [comment]
We are also seeing this issue on a private reposity. I've tried running with `--debug`, but it seems the error occurs before there is any useful debugging information.

Do you have any other suggestions on trying to get useful errors? Any output that could help make a minimal reproducer without just randomly trying things.

**Comment by dosisod** [comment]
This is an issue with how Mypy resolves package names internally, though I have no idea why it is causing issues here. I am having troubles reproducing this reliably on my machine, that is to say, Mypy has lots of quirks when it comes down to how it does module resolution.

If your filenames aren't too sensitive, could you post the output of `tree problematic/folder/here`? The issue seems to be with the naming/structure of the files and folders, not so much the content of the files. If you can, try to narrow it down to a specific folder which is causing Refurb to give you a duplicate module error.

As far as I can tell, here is what *could* be causing Mypy to think it is getting duplicate results:

* Files/folders with dashes (`-`) in them
* Placement of `__init__.py` files (in certain circumstances)
* Files/folders that share the same name as another file/folder in the same project (see #101)

Sorry if this is preventing you from using Refurb! I am looking into this, but the issue seems to be with Mypy (or how I am calling Mypy). As a quick-fix you could use `refurb folder -- --exclude some/folder` to tell Mypy to exclude `some/folder`.

**Comment by nth10sd** [comment]
I've found adding `-- -p <package>`, helps more than adding `-- --exclude some/folder`.

**Comment by jamesbraza** [comment]
To repost a solution from https://github.com/astral-sh/rye/issues/1246 here for posterity, I was able to decisively resolve this issue without `--exclude` or pre-`cd` awkwardness by configuring `mypy_path`.
