### ISSUE TITLE
[Enhancement]: looping over `open` without closing

### ISSUE THREAD

**Issue by sbrugman** [dosisod/refurb#266]
### Overview

While working on porting some pathlib rules to `ruff`, I encountered that people open files in the context of looping over them without closing:

```python
[x.rstrip() for x in open(args.save_path).readlines()]
```

```python
for line in open('file_name.txt'):
    ...
```

https://grep.app/search?q=%20in%20open%28&filter%5Blang%5D%5B0%5D=Python

### Proposal

I'd suggest detecting these cases and recommend to use a context manager.

**Comment by dosisod** [comment]
This seems to be already covered by the [`SIM115`](https://beta.ruff.rs/docs/rules/open-file-with-context-handler/) rule in Ruff.

In general I have been pretty hesitant to add rules/checks that are in other linters (such as Ruff) because it creates overlap without adding anything unique: I want Refurb to include checks that aren't available in other linters so that people will continue to use/find value in Refurb.

**Comment by sbrugman** [comment]
Great spot, completely overlooked that rule as it wasn't in the context of `flake8-use-pathlib`.
