### ISSUE TITLE
[Bug]: refurb --explain FURB179 has bad code

### ISSUE THREAD

**Issue by shaolo1** [dosisod/refurb#298]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

refurb --explain FURB179
outputs 
flat = chain.from_iterable(*rows)
 but should be
flat = chain.from_iterable(rows)
Interestingly it was correct in the release notes

### Version Info

```shell
Refurb: v1.22.0
Mypy: v1.6.0
```

### Python Version

Python 3.10.12

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you for opening this! I tweaked it in the release notes but forgot to fix it in the code. I'll fix that right now.

The `list()` wrapping issue will require a bit more work due to how Refurb handles list comprehensions and generators internally. If I were to properly handle list comprehensions there would be 2 errors emitted, one for the list comprehension, and one for the inner generator since list comprehensions are wrappers around generators internally. This change would unblock some other things I've been unable to do, so I'll fix this soon.
