### ISSUE TITLE
[Bug]: FURB148 generated when _ used as variable name

### ISSUE THREAD

**Issue by shaolo1** [dosisod/refurb#311]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
values = [{'name': 'foo', 'file': 'foo.txt'}, {'name': 'bar', 'file': 'bar.txt'}]
keys_values = {f':file_{i}': x['file'] for i, x in enumerate(values)}  # no warning
print(keys_values)
keys_values = {f':file_{i}': _['file'] for i, _ in enumerate(values)}  # same as above, but using _ as the variable name generates FURB148
print(keys_values)
```

Emits the following error:

```
$ refurb file.py
[FURB148]: Value is unused, use `for x in range(len(y))` instead
```

But it should not be emitting an error instance because...the value is not unused.

### Version Info

```shell
Refurb: v1.24.0
Mypy: v1.7.0
```

### Python Version

Python 3.11.3

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you @shaolo1 for opening this! This is indeed a bug, and it should be easy to fix (with some exceptions): It is easy to detect whether a variable is used or not within generators/comprehensions since those have their own scopes, but for loops are a bit harder since the variables bleed out after the loop is finished:

```python
l = [x for x in range(100)]
# print(x)  # err, x not defined

for x in range(100):
    pass
print(x)  # prints 99
```

Since Refurb only checks the generator/comprehension/for loop body, it cannot tell if it is used outside of that scope. As a workaround I also treated `_` variables as unused, since `_` is typically used as a placeholder/discard variable. As your issue points out though, this check is also being applied to comprehensions when it should only be used in for loops, which is an easy enough fix.

And with for loops, I doubt many people rely on the variables leaking to the outer scope, so it should be safe to ignore `_` variables in general and just treat them like any other variable. I might make a separate check for usage of `_` as variable names since that can cause confusion.

**Comment by shaolo1** [comment]
You guys rock! Thanks for all the good work!!

**Comment by pums974** [comment]
> And with for loops, I doubt many people rely on the variables leaking to the outer scope ...

Hi, I agree with the rest of your message, but there is this very common pattern:

```
for stuff in thing:
   if some_property(stuff):
        break

do_something(stuff)
```

**Comment by dosisod** [comment]
@pums974 in your example `stuff` is used in the body of the loop, so an error message wouldn't be emitted. A case where it would be an issue though would be if `stuff` is never used in the body of the loop and is only used after the loop finishes, in which case an error would be emitted when it shouldn't.

Regardless, I need to do some brainstorming to figure out how to fix this, since fixing this would help fix a few other issues in Refurb as well.
